# Generated by Django 6.0 on 2025-12-09 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCategoryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('base_point_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.card')),
                ('merchant_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.merchantcategory')),
                ('merchant_category_codes', models.ManyToManyField(blank=True, to='recommendation.merchantcategorycode')),
            ],
        ),
        migrations.CreateModel(
            name='RewardRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cashback_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('reset_period', models.CharField(blank=True, max_length=50)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reward_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommendation.rewardcategory')),
            ],
        ),
    ]
